/**
 * File storage on disk — item images live as real files, not DB blobs.
 * (Same pattern as Wholesale HQ's attachment storage.)
 *
 * On Render, set STORAGE_DIR to the mounted Persistent Disk path (e.g. /data)
 * so files survive deploys/restarts. Locally it defaults to ./.storage. The DB
 * only keeps a small `image_key` pointing at the file here.
 */
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { env } from "../env.js";

const ROOT = env.STORAGE_DIR?.trim() || path.resolve(process.cwd(), ".storage");
const IMAGE_DIR = path.join(ROOT, "item-images");

/** Allowed image types; the extension doubles as the stored content type. */
export const IMAGE_MIMES: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
};

const EXT_TO_MIME: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
};

function ensureDir(): void {
  fs.mkdirSync(IMAGE_DIR, { recursive: true });
}

/** Keys are generated by us (uuid + ext), but never trust one off the wire —
 *  strip any path parts so a key can't escape the images directory. */
function resolveKey(key: string): string {
  return path.join(IMAGE_DIR, path.basename(key));
}

/** Persist an image's bytes; returns the storage key to save in the DB. */
export function saveItemImage(buf: Buffer, mime: string): string {
  ensureDir();
  const ext = IMAGE_MIMES[mime];
  if (!ext) throw new Error(`Unsupported image type: ${mime}`);
  const key = `${randomUUID()}.${ext}`;
  fs.writeFileSync(path.join(IMAGE_DIR, key), buf);
  return key;
}

/** Read an image's bytes back, with its content type. Throws if missing. */
export function readItemImage(key: string): { buf: Buffer; mime: string } {
  const buf = fs.readFileSync(resolveKey(key));
  const ext = key.split(".").pop() ?? "";
  return { buf, mime: EXT_TO_MIME[ext] ?? "application/octet-stream" };
}

/** Best-effort delete (never throws — the row update matters more). */
export function deleteItemImage(key: string | null | undefined): void {
  if (!key) return;
  try {
    fs.unlinkSync(resolveKey(key));
  } catch {
    /* already gone */
  }
}
